// <auto-generated />
using System;
using MarikinaMarket.API.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarikinaMarket.API.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260804104510_UpdatedTicketEntity")]
    partial class UpdatedTicketEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("UserSequence", "shared");

            modelBuilder.Entity("MarikinaMarket.API.Domain.Entities.MarketSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_market_sections");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_market_sections_name");

                    b.ToTable("market_sections", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Designated area for vendors selling fresh fish, shellfish, and other marine products. Subject to strict sanitation standards and daily cleaning requirements per Chapter VIII of the Market Code of 2014.",
                            Name = "Fish and Seafood Section"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Designated area for vendors selling all kinds of meat and meat products that passed the inspection of the City Veterinary Office in accordance with National Meat Inspection Commission standards. Wooden furniture prohibited per Section 58 of Market Code 2014.",
                            Name = "Meat Section"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Designated area for vendors selling textiles, modiste and tailor supplies, accessories, apparels, native products, toiletries, novelties, toys, footwear, kitchenwares, household articles, handbags, and office supplies per Section 21(c) of the Market Code of 2014.",
                            Name = "Dry Goods Section"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Designated area for vendors selling all kinds of vegetables, fruits, coconuts, root crops such as camote, cassava, gabi, and other farm products per Section 21(f) of the Market Code of 2014.",
                            Name = "Vegetable Section"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Designated area for vendors selling bakery products, dairy, cold cuts, processed meat, condiments, cigarettes, soap, charcoal, and canned, bottled, boxed or sachet food products per Section 21(e) of the Market Code of 2014.",
                            Name = "Groceries Section"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Designated area for vendors selling all kinds of cooked and prepared food. Food Safety and Personal Hygiene Training required for all eatery owners and helpers per Section 14 of the Market Code of 2014. Highest sanitation standards enforced under Chapter VIII.",
                            Name = "Eatery Section"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Designated area for special commercial establishments including restaurants, pawnshops, hardware stores, drug stores, beauty parlors, internet cafes, flower shops, gift shops, magazine stands, and bayad centers per Section 21(d) of the Market Code of 2014.",
                            Name = "Special Stalls"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Designated area for any other business not classified under the established market sections per Section 21(h) of the Market Code of 2014. Subject to all general market rules and sanitation standards.",
                            Name = "Miscellaneous Section"
                        });
                });

            modelBuilder.Entity("MarikinaMarket.API.Domain.Entities.Ordinance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("OrdinanceNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ordinance_no");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_ordinances");

                    b.HasIndex("OrdinanceNo")
                        .IsUnique()
                        .HasDatabaseName("ix_ordinances_ordinance_no");

                    b.ToTable("ordinances", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Obstruction",
                            Code = "Market Code",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sections 42, 47, and 53 of the Revised Marikina Market Code of 2014 (amending Ordinance No. 149, Series of 1999) prohibit peddling or hawking in passageways, placing items on corridors and walkways, and conducting any vending activities on streets and sidewalks within the Marikina Public Market Zone. Stall holders must strictly observe their designated stall boundaries at all times.",
                            OrdinanceNo = "Ord. No. 11, Series of 2014",
                            Title = "Revised Marikina Market Code of 2014 — Stall Boundary and Walkway Violations"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Noise",
                            Code = "Peace & Order Code",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Section 32 of the Revised Marikina Peace, Order, Public Safety and Security Code of 2006 regulates noise and revelries within the City. Audio-amplified equipment such as stereos, karaokes, videoke, and similar musical devices shall not play beyond normally accepted sound modulation after 10:00 PM. Market vendors are additionally prohibited from using sidewalks and streets as extensions of their stalls under Section 5, subject to fine of P1,000 and confiscation of goods. Alternative penalties including blood donation (for fines not exceeding P1,000) and community service are authorized under Appendix B.",
                            OrdinanceNo = "Ord. No. 145, Series of 2006",
                            Title = "Revised Marikina Peace, Order, Public Safety and Security Code of 2006"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Licensing",
                            Code = "Market I.D.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ordinance No. 104, Series of 2007 amends Section 12 of the Marikina Market Code requiring all vendors and helpers in public and private markets within the City of Marikina to secure and display a valid Market Identification Card at all times. The Market ID costs Seventy-Five Pesos (P75.00) and must be renewed annually. Operating without a valid Market ID or business permit constitutes a violation subject to penalties under Section 79 of the Market Code of 2014.",
                            OrdinanceNo = "Ord. No. 104, Series of 2007",
                            Title = "Ordinance Amending Section 12 of the Marikina Market Code — Market Identification Card Requirements"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Sanitation",
                            Code = "Market Code",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chapter VIII (Sections 66–75) of the Revised Marikina Market Code of 2014 governs the maintenance of market premises and sanitation standards. Stallholders must keep stalls clean at all times, use impervious materials on counters and walls per Section 72, protect cooked and raw foods from contamination per Section 70, clean stalls at the end of each business day per Section 73, and properly dispose of garbage per Section 69. All food eatery owners must complete Food Safety and Personal Hygiene Training per Section 14. A fine of One Thousand Pesos (P1,000.00) is imposed per violation. Third violation results in cancellation of license.",
                            OrdinanceNo = "Ord. No. 11, Series of 2014 — Chapter VIII",
                            Title = "Revised Marikina Market Code of 2014 — Sanitation and Cleanliness Standards"
                        },
                        new
                        {
                            Id = 5,
                            Category = "WeightMeasures",
                            Code = "Market Code",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chapter VI, Section 30 of the Revised Marikina Market Code of 2014 (amending Ordinance No. 160, Series of 2001 and Ordinance No. 283, Series of 1997) prohibits the use of underweight scales, placement of concealed materials in weighing scales, and any manipulation that reflects a weight other than the true weight of goods. All weighing devices must be registered with the City Treasury and submitted for annual re-inspection. Confiscated scales must be redeemed within five (5) working days. A specific graduated penalty schedule applies independently from the general market code penalties.",
                            OrdinanceNo = "Ord. No. 11, Series of 2014 — Chapter VI",
                            Title = "Revised Marikina Market Code of 2014 — Weights and Measures Compliance"
                        });
                });

            modelBuilder.Entity("MarikinaMarket.API.Domain.Entities.OrdinancePenaltyTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OffenseNumber")
                        .HasColumnType("integer")
                        .HasColumnName("offense_number");

                    b.Property<int>("OrdinanceId")
                        .HasColumnType("integer")
                        .HasColumnName("ordinance_id");

                    b.Property<decimal>("PenaltyAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("penalty_amount");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.HasKey("Id")
                        .HasName("pk_ordinance_penalty_tiers");

                    b.HasIndex("OrdinanceId", "OffenseNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_ordinance_penalty_tiers_ordinance_id_offense_number");

                    b.ToTable("ordinance_penalty_tiers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OffenseNumber = 1,
                            OrdinanceId = 1,
                            PenaltyAmount = 1000.00m,
                            Severity = "Low"
                        },
                        new
                        {
                            Id = 2,
                            OffenseNumber = 2,
                            OrdinanceId = 1,
                            PenaltyAmount = 1500.00m,
                            Severity = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            OffenseNumber = 3,
                            OrdinanceId = 1,
                            PenaltyAmount = 2000.00m,
                            Severity = "High"
                        },
                        new
                        {
                            Id = 4,
                            OffenseNumber = 4,
                            OrdinanceId = 1,
                            PenaltyAmount = 5000.00m,
                            Severity = "High"
                        },
                        new
                        {
                            Id = 5,
                            OffenseNumber = 1,
                            OrdinanceId = 2,
                            PenaltyAmount = 500.00m,
                            Severity = "Low"
                        },
                        new
                        {
                            Id = 6,
                            OffenseNumber = 2,
                            OrdinanceId = 2,
                            PenaltyAmount = 1000.00m,
                            Severity = "Medium"
                        },
                        new
                        {
                            Id = 7,
                            OffenseNumber = 3,
                            OrdinanceId = 2,
                            PenaltyAmount = 2000.00m,
                            Severity = "High"
                        },
                        new
                        {
                            Id = 8,
                            OffenseNumber = 4,
                            OrdinanceId = 2,
                            PenaltyAmount = 3000.00m,
                            Severity = "High"
                        },
                        new
                        {
                            Id = 9,
                            OffenseNumber = 1,
                            OrdinanceId = 3,
                            PenaltyAmount = 100.00m,
                            Severity = "Low"
                        },
                        new
                        {
                            Id = 10,
                            OffenseNumber = 2,
                            OrdinanceId = 3,
                            PenaltyAmount = 500.00m,
                            Severity = "Medium"
                        },
                        new
                        {
                            Id = 11,
                            OffenseNumber = 3,
                            OrdinanceId = 3,
                            PenaltyAmount = 1000.00m,
                            Severity = "High"
                        },
                        new
                        {
                            Id = 12,
                            OffenseNumber = 4,
                            OrdinanceId = 3,
                            PenaltyAmount = 2000.00m,
                            Severity = "High"
                        },
                        new
                        {
                            Id = 13,
                            OffenseNumber = 1,
                            OrdinanceId = 4,
                            PenaltyAmount = 1000.00m,
                            Severity = "Medium"
                        },
                        new
                        {
                            Id = 14,
                            OffenseNumber = 2,
                            OrdinanceId = 4,
                            PenaltyAmount = 1500.00m,
                            Severity = "High"
                        },
                        new
                        {
                            Id = 15,
                            OffenseNumber = 3,
                            OrdinanceId = 4,
                            PenaltyAmount = 2000.00m,
                            Severity = "High"
                        },
                        new
                        {
                            Id = 16,
                            OffenseNumber = 1,
                            OrdinanceId = 5,
                            PenaltyAmount = 1500.00m,
                            Severity = "Medium"
                        },
                        new
                        {
                            Id = 17,
                            OffenseNumber = 2,
                            OrdinanceId = 5,
                            PenaltyAmount = 3000.00m,
                            Severity = "High"
                        },
                        new
                        {
                            Id = 18,
                            OffenseNumber = 3,
                            OrdinanceId = 5,
                            PenaltyAmount = 5000.00m,
                            Severity = "High"
                        },
                        new
                        {
                            Id = 19,
                            OffenseNumber = 4,
                            OrdinanceId = 5,
                            PenaltyAmount = 5000.00m,
                            Severity = "High"
                        });
                });

            modelBuilder.Entity("MarikinaMarket.API.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("MarikinaMarket.API.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int[]>("Categories")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("categories");

                    b.Property<int?>("CommunityServiceHours")
                        .HasColumnType("integer")
                        .HasColumnName("community_service_hours");

                    b.Property<string>("ControlNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("control_number");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("EnforcerId")
                        .HasColumnType("integer")
                        .HasColumnName("enforcer_id");

                    b.Property<string>("HighestSeverity")
                        .HasColumnType("text")
                        .HasColumnName("highest_severity");

                    b.Property<DateTime>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<int>("MarketSectionId")
                        .HasColumnType("integer")
                        .HasColumnName("market_section_id");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_status");

                    b.Property<string>("PenaltyType")
                        .HasColumnType("text")
                        .HasColumnName("penalty_type");

                    b.Property<string>("ReceiptUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("receipt_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalPaymentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_payment_amount");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("ControlNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_tickets_control_number");

                    b.HasIndex("EnforcerId")
                        .HasDatabaseName("ix_tickets_enforcer_id");

                    b.HasIndex("MarketSectionId")
                        .HasDatabaseName("ix_tickets_market_section_id");

                    b.HasIndex("VendorId", "Categories", "IssuedAt")
                        .HasDatabaseName("ix_tickets_vendor_id_categories_issued_at");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("MarikinaMarket.API.Domain.Entities.TicketEvidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EvidenceUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("evidence_url");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_evidences");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_ticket_evidences_ticket_id");

                    b.ToTable("ticket_evidences", (string)null);
                });

            modelBuilder.Entity("MarikinaMarket.API.Domain.Entities.TicketViolation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OffenseCount")
                        .HasColumnType("integer")
                        .HasColumnName("offense_count");

                    b.Property<int>("OrdinanceId")
                        .HasColumnType("integer")
                        .HasColumnName("ordinance_id");

                    b.Property<decimal?>("PenaltyAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("penalty_amount");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_violations");

                    b.HasIndex("OrdinanceId")
                        .HasDatabaseName("ix_ticket_violations_ordinance_id");

                    b.HasIndex("TicketId", "OrdinanceId")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_violations_ticket_id_ordinance_id");

                    b.ToTable("ticket_violations", (string)null);
                });

            modelBuilder.Entity("MarikinaMarket.API.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("middle_name");

                    b.Property<bool>("MustChangedPassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_changed_password");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("ix_asp_net_users_user_name");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MarikinaMarket.API.Domain.Entities.VendorProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("business_name");

                    b.Property<int>("ComplianceScore")
                        .HasColumnType("integer")
                        .HasColumnName("compliance_score");

                    b.Property<int>("MarketSectionId")
                        .HasColumnType("integer")
                        .HasColumnName("market_section_id");

                    b.Property<string>("QrCodeValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qr_code_value");

                    b.Property<DateTime>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<DateTime>("ScoreUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("score_updated_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("StallNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stall_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_vendor_profiles");

                    b.HasIndex("QrCodeValue")
                        .IsUnique()
                        .HasDatabaseName("ix_vendor_profiles_qr_code_value");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_vendor_profiles_user_id");

                    b.HasIndex("MarketSectionId", "StallNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_vendor_profiles_market_section_id_stall_number");

                    b.ToTable("vendor_profiles", (string)null);
                });

            modelBuilder.Entity("MarikinaMarket.API.Domain.Entities.VendorRegistrationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessDocumentPhotoUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("business_document_photo_url");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("business_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("GovernmentIdNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("government_id_number");

                    b.Property<string>("GovernmentIdPhotoUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("government_id_photo_url");

                    b.Property<string>("GovernmentIdType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("government_id_type");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<int>("MarketSectionId")
                        .HasColumnType("integer")
                        .HasColumnName("market_section_id");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("password");

                    b.Property<DateTime>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("integer")
                        .HasColumnName("reviewed_by");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<string>("StallNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stall_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_vendor_registration_requests");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_vendor_registration_requests_email");

                    b.HasIndex("MarketSectionId")
                        .HasDatabaseName("ix_vendor_registration_requests_market_section_id");

                    b.HasIndex("ReviewedBy")
                        .HasDatabaseName("ix_vendor_registration_requests_reviewed_by");

                    b.ToTable("vendor_registration_requests", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "a72b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "b83c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e",
                            Name = "Enforcer",
                            NormalizedName = "ENFORCER"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "c94d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f",
                            Name = "Vendor",
                            NormalizedName = "VENDOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MarikinaMarket.API.Domain.Entities.OrdinancePenaltyTier", b =>
                {
                    b.HasOne("MarikinaMarket.API.Domain.Entities.Ordinance", "Ordinance")
                        .WithMany("PenaltyTiers")
                        .HasForeignKey("OrdinanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ordinance_penalty_tiers_ordinances_ordinance_id");

                    b.Navigation("Ordinance");
                });

            modelBuilder.Entity("MarikinaMarket.API.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("MarikinaMarket.API.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MarikinaMarket.API.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("MarikinaMarket.API.Domain.Entities.User", "Enforcer")
                        .WithMany("IssuedTickets")
                        .HasForeignKey("EnforcerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_users_enforcer_id");

                    b.HasOne("MarikinaMarket.API.Domain.Entities.MarketSection", "MarketSection")
                        .WithMany("Tickets")
                        .HasForeignKey("MarketSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_market_sections_market_section_id");

                    b.HasOne("MarikinaMarket.API.Domain.Entities.VendorProfile", "Vendor")
                        .WithMany("Tickets")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_vendor_profiles_vendor_id");

                    b.Navigation("Enforcer");

                    b.Navigation("MarketSection");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("MarikinaMarket.API.Domain.Entities.TicketEvidence", b =>
                {
                    b.HasOne("MarikinaMarket.API.Domain.Entities.Ticket", "Ticket")
                        .WithMany("TicketEvidences")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_evidences_tickets_ticket_id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("MarikinaMarket.API.Domain.Entities.TicketViolation", b =>
                {
                    b.HasOne("MarikinaMarket.API.Domain.Entities.Ordinance", "Ordinance")
                        .WithMany("TicketViolations")
                        .HasForeignKey("OrdinanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_violations_ordinances_ordinance_id");

                    b.HasOne("MarikinaMarket.API.Domain.Entities.Ticket", "Ticket")
                        .WithMany("TicketViolations")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_violations_tickets_ticket_id");

                    b.Navigation("Ordinance");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("MarikinaMarket.API.Domain.Entities.VendorProfile", b =>
                {
                    b.HasOne("MarikinaMarket.API.Domain.Entities.MarketSection", "MarketSection")
                        .WithMany("VendorProfiles")
                        .HasForeignKey("MarketSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vendor_profiles_market_sections_market_section_id");

                    b.HasOne("MarikinaMarket.API.Domain.Entities.User", "User")
                        .WithOne("VendorProfile")
                        .HasForeignKey("MarikinaMarket.API.Domain.Entities.VendorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vendor_profiles_users_user_id");

                    b.Navigation("MarketSection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MarikinaMarket.API.Domain.Entities.VendorRegistrationRequest", b =>
                {
                    b.HasOne("MarikinaMarket.API.Domain.Entities.MarketSection", "MarketSection")
                        .WithMany()
                        .HasForeignKey("MarketSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vendor_registration_requests_market_sections_market_section");

                    b.HasOne("MarikinaMarket.API.Domain.Entities.User", "ReviewedByUser")
                        .WithMany("ReviewedVendorRegistrationRequests")
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_vendor_registration_requests_asp_net_users_reviewed_by");

                    b.Navigation("MarketSection");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("MarikinaMarket.API.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("MarikinaMarket.API.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("MarikinaMarket.API.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("MarikinaMarket.API.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("MarikinaMarket.API.Domain.Entities.MarketSection", b =>
                {
                    b.Navigation("Tickets");

                    b.Navigation("VendorProfiles");
                });

            modelBuilder.Entity("MarikinaMarket.API.Domain.Entities.Ordinance", b =>
                {
                    b.Navigation("PenaltyTiers");

                    b.Navigation("TicketViolations");
                });

            modelBuilder.Entity("MarikinaMarket.API.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("TicketEvidences");

                    b.Navigation("TicketViolations");
                });

            modelBuilder.Entity("MarikinaMarket.API.Domain.Entities.User", b =>
                {
                    b.Navigation("IssuedTickets");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ReviewedVendorRegistrationRequests");

                    b.Navigation("VendorProfile");
                });

            modelBuilder.Entity("MarikinaMarket.API.Domain.Entities.VendorProfile", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
